version: '3.8'

services:
  adonis_backend2:
    container_name: adonis_backend2
    image: cashmanager/website_backend:develop
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - '8080:8080'
    depends_on:
      - database_mariadb2
      - phpmyadmin2
    networks:
      - app-network

  database_mariadb2:
    container_name: database_mariadb2
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cashmanager_develop
      MYSQL_USER: adonis
      MYSQL_PASSWORD: adonis
    ports:
      - '3800:3306'
    volumes:
      - database_data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin2:
    container_name: phpmyadmin2
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: database_mariadb2
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - '8050:80'
    networks:
      - app-network

networks:
  app-network:

volumes:
  database_data:
  app:
  node_modules:
